from .base import BaseTechnique
from .gensim_lsi_similarity import GensimLsiSimilarity
from .sbert_semantic_search import SbertSemanticSearch
from .equality_comparison import EqualityComparison
from .kg_similarity.bow_similarity import KnowledgeGraphBagOfWordsSimilarity
